### PR TITLE
fix: panic when listing session that have an invalid LastAttached time

### LINKED ISSUE #34: Panic in sesh/tmux/list.go running sesh list -t
Thanks for the hard work on this package!

I'm trying to configure my dev environment with multiple tmux sessions orchestrated using tmuxinator. I've simplified the environment to 2 sessions to illustrate the issue. Running `sesh list -t` panics with an NPE.

As far as I can tell, tmuxinator isn't doing anything particularly out of the ordinary when creating a session https://github.com/search?q=repo:tmuxinator/tmuxinator%20new-session&type=code.

Here's a text version of the stack trace
```
❯ sesh list -t
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1045a2bcc]

goroutine 1 [running]:
github.com/joshmedeski/sesh/tmux.List.func1(0x30?, 0x1047ddec0?)
	/home/runner/work/sesh/sesh/tmux/list.go:150 +0x3c
sort.insertionSort_func({0x140000f9460?, 0x140000c5360?}, 0x0, 0x2)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sort/zsortfunc.go:12 +0xc0
sort.pdqsort_func({0x140000f9460?, 0x140000c5360?}, 0x18?, 0x1047ddec0?, 0x140000b0420?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sort/zsortfunc.go:73 +0x260
sort.Slice({0x104671d20?, 0x140000b0420?}, 0x2?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sort/slice.go:26 +0xfc
github.com/joshmedeski/sesh/tmux.List()
	/home/runner/work/sesh/sesh/tmux/list.go:149 +0x768
github.com/joshmedeski/sesh/session.List({0x18?, 0x0?})
	/home/runner/work/sesh/sesh/session/list.go:17 +0x6c
github.com/joshmedeski/sesh/seshcli.App.List.func1(0x1400012c000?)
	/home/runner/work/sesh/sesh/cmds/list.go:31 +0x50
github.com/urfave/cli/v2.(*Command).Run(0x1400012c000, 0x140000a84c0, {0x140000c49c0, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.0/command.go:279 +0x754
github.com/urfave/cli/v2.(*Command).Run(0x1400012c6e0, 0x140000a8380, {0x1400009c090, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.0/command.go:272 +0x964
github.com/urfave/cli/v2.(*App).RunContext(0x14000128000, {0x1046aaf48?, 0x104811420}, {0x1400009c090, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.0/app.go:337 +0x534
github.com/urfave/cli/v2.(*App).Run(0x10460ed68?, {0x1400009c090?, 0x0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.0/app.go:311 +0x3c
main.main()
	/home/runner/work/sesh/sesh/main.go:14 +0xb0
```

CleanShot 2024-01-20 at 15 21 19@2x

### PR DESCRIPTION
**Pull request by markfeinstein**
Change the behavior of `StringToTime` to return a zero value `*time.Time` rather than a `nil` to prevent a panic when sorting a slice of sessions. 

fixes #34 

Additional changes
- Update deps `go get -u all`
- Add `testify` package for unit testing
- Add functional and benchmark tests
- Refactor `format` function for performance improvements
- Extract session data processing code to improve testability and minor readability improvements

### CODE REVIEW

File: tmux/list_test.go [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+		})
+	}
+}
+
+// BenchmarkProcessSessions
+//   - Initial:
+//     BenchmarkProcessSessions-10  817090  1405 ns/op 1712 B/op  29 allocs/op
+//   - Refactored:
+//     BenchmarkProcessSessions-10  1692590  709.8 ns/op  744 B/op  4 allocs/op
+func BenchmarkProcessSessions(b *testing.B) {
```
Comment (joshmedeski) [inline tmux/list_test.go:91]: How does benchmarking work? Does the code comment update or did you just copy/paste the verbose test results?

Furthermore, can we make an assertion to ensure the benchmarking doesn't hit a upper-limit to investigate if tmux has some performance issues in a future version?

File: convert/string.go [hunk 2]
```diff
@@ -9,16 +9,19 @@ import (
...
+		return t
 	}
+
 	i, err := strconv.ParseInt(s, 10, 64)
 	if err != nil {
 		fmt.Println("Error:", err)
 		os.Exit(1)
 	}
-	t := time.Unix(i, 0)
-	return &t
```
Comment (joshmedeski) [inline convert/string.go:21]: Is it best practice to avoid returning `&t`? I'm still new to GoLang and want to make sure I'm doing a better job leveraging the language.

**Review by joshmedeski — CHANGES_REQUESTED** [review]
Just a few minor things, great work!

File: tmux/list_test.go (hunk 1 above)
Comment (markfeinstein) [reply tmux/list_test.go:91]: The benchmark tests get run when by `go test` when you add the appropriate flags. In this case by running `go test -bench=. -benchmem` in the `tmux` directory. 

The comments with the results are something I added manually as I was working through the code.

There isn't anything in the standard lib that would establish a performance criteria for these tests. You could probably implement something manually, but I imagine it would be too flakey to be beneficial. Subtle differences between systems or their running state can have significant effects on the benchmark tests.

Comment (joshmedeski) [reply tmux/list_test.go:91]: Do you think it's a good idea to remove the benchmark comments then? I'm not sure what value they have now that you've resolved the performance issue.

File: convert/string.go (hunk 2 above)
Comment (markfeinstein) [reply convert/string.go:21]: Pointers tend to add complexity so it's better to avoid them unless you need them. In this case I'd just return `time.Time`.

File: tmux/list_test.go (hunk 1 above)
Comment (markfeinstein) [reply tmux/list_test.go:79]: Sure. Dropped the comments.

**Comment by joshmedeski** [comment]
Thanks for this work! I'll start using testify and will be adding more tests 👍
